### PR TITLE
ensure for link & symlink

### PR DESCRIPTION
**Pull request by reggi**

### CODE REVIEW

**Comment by reggi** [comment]
@jprichardson

Added:

* error messages use lstat and replace the string `lstat` with `ensureSymlink` and `ensureLink` respectivley
* will not create recursive destination directories on error 
* branched out feature and dev so you can see diffs between pull-requests [here](https://github.com/reggi/node-fs-extra/commits/dev/ensurelink-ensuresymlink)

**Comment by reggi** [comment]
Should an error be thrown if the destination path exists?

**Comment by jprichardson** [comment]
> Should an error be thrown if the destination path exists?

I don't think so.

Thanks for your hard work on this, I really appreciate it! Published `0.23.0`.

**Comment by reggi** [comment]
The functions currently return an error for async and throw for sync if the destination path exists because that's the native functionality of `fs.link` and `fs.symlink` is exposed.

**Comment by jprichardson** [comment]
Yeah, I think that they should be normalized to not throw errors if the destination exists. I mean, the intent of the caller of these methods is to just make sure that they exist regardless of whether they existed before said method was called. Don't you think?

**Comment by reggi** [comment]
As expressed [here](https://github.com/jprichardson/node-fs-extra/issues/164#issuecomment-128069620) I feel weird throwing the err away. My current usage for this function is as follows, please forgive the promises.

```
fse.ensureLinkAsync(pkg.main, paths.mainDst)
.then(debugThen('linking main %s -> %s', pkg.main, paths.mainDst)).catch(debugCatch),
```

So for control-flow it's useful to know if something has been created or not. 

Thats why [I expressed the need for `ensureWarn` functions](https://github.com/jprichardson/node-fs-extra/issues/164#issuecomment-128083607). 

I agree though with this:

> the intent of the caller of these methods is to just make sure that they exist regardless

Crafting PR(s) now.

**Comment by reggi** [comment]
https://github.com/jprichardson/node-fs-extra/pull/169

**Pull request merged**
