### PR TITLE
Remove unneeded and buggy stats check

### PR DESCRIPTION
**Pull request by RyanZim**
As per https://github.com/nodejs/node/pull/39372#discussion_r1001179295; haven't gotten a response from @bcoe there yet

Resolves https://github.com/jprichardson/node-fs-extra/issues/918

Hope this logic is right.

### CODE REVIEW

**Comment by RyanZim** [comment]
@manidlou @bcoe bump

**Comment by RyanZim** [comment]
I have been trying to write a test case for this; I cannot get to a place where this condition is ever reached. Do we need this at all? Or what am I missing?

**Comment by manidlou** [comment]
This is basically a wild edge case where we're trying to avoid broken copy when src is a link and its resolved path is inside the dest directory. We already have this test

https://github.com/jprichardson/node-fs-extra/blob/e6a95058c930953113177c9518f57e83cace3e79/lib/copy/__tests__/copy-prevent-copying-into-itself.test.js#L282-L296

what's wrong with this test?

**Comment by RyanZim** [comment]
@manidlou The problem is that that test doesn't actually exercise this condition. We'd expect the error to be of the format:

    Cannot overwrite '${resolvedDest}' with '${resolvedSrc}'.

Instead, if you insert a log statement in that test, the actual error thrown is:

    Error: Cannot overwrite directory '/tmp/fs-extra/copy-prevent-copying-into-itself/dest' with non-directory '/tmp/fs-extra/copy-prevent-copying-into-itself/src-symlink'.

**Comment by RyanZim** [comment]
I'm going to merge this as-is, without an explicit test, as it's certainly better than what we have now. However, we should still look into properly testing this later.

**Comment by manidlou** [comment]
Thank you @RyanZim! That makes sense.

**Pull request merged**
