### PR TITLE
move() should error when src & dest are the same and src doesn't exist

### LINKED ISSUE #414: fs.move doesn't return error on moving same nonexistent folder/file
#### Issue:
When i `fs.move()` using two paths that are the same and both are invalid(nonexistent) paths, the function does not return an error, which it should since you are trying to move a nonexistent path.

#### Setup:
This is being ran inside of an electron render, which means its being ran inside of a chrome wrapper. This issue persists through fs-extra 3.0

#### Example:
`fs.move("nonexistent/path","nonexistent/path", (err) => { console.log(err)})`
`// err returns null`

#### Usage:
I use this in my personal repo:
https://github.com/zosman1/The_Archiver/blob/c65ed9dfb7ae0855b1fcb8026204c8d6876a96af/app/index.js#L25

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #414; bug introduced in #378

@jprichardson What's your opinion on semver for this patch?

### CODE REVIEW

**Comment by manidlou** [comment]
Thanks @RyanZim :+1:

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by RyanZim** [comment]
@jprichardson Want this released? What semver?

**Comment by jprichardson** [comment]
> @jprichardson Want this released? What semver?

yeah, `3.0.1`

**Pull request merged**
