### PR TITLE
Added walkSync function

### PR DESCRIPTION
**Pull request by agnivade**

### CODE REVIEW

**Comment by agnivade** [comment]
Closes #240

**Comment by RyanZim** [comment]
@jprichardson Thoughts on this?

**Comment by jprichardson** [comment]
I'm fine with keeping it in here. I really like how `klaw` simply just returns an async walker that is a ReadableStream. What are your thoughts @RyanZim?

**Comment by RyanZim** [comment]
IDK, assigning to you.

**Comment by jprichardson** [comment]
@agnivade what's your use case for `walkSync()`? i.e. why not just use the more efficient `walk()`?

**Comment by agnivade** [comment]
I am working on a codebase which has used `sync` counterparts of all fs operations. Using the `async` versions will make it very hard to integrate. 

And moreover, if you are providing `sync` counterparts of all other `fs` operations, it only makes sense to add it for the `walk` functionality.

**Comment by levithomason** [comment]
Same here, I'm working on a CLI that is loading a config file.  The entire bootstrap process and config loading is sync.  I need to read a dir sync and add all the paths found to some config.  If I go async here, the entire CLI bootstrapping needs to be rewritten to handle async.  It is also more complicated to handle async bootstrapping.

My use case was solved by [fs-readdir-recursive](https://github.com/fs-utils/fs-readdir-recursive), though I'd much rather not have another for one task.  I don't need the extra params provided by walk so my use case was a little more simple.

**Pull request merged**
