### PR TITLE
Implement GH actions

### PR DESCRIPTION
**Pull request by RyanZim**

### CODE REVIEW

**Comment by RyanZim** [comment]
For some reason, `fs.symlink*()` itself seems to behave differently in Windows on GH Actions than in AppVeyor.

**Comment by RyanZim** [comment]
The tests that are breaking aren't actually testing fs-extra, they're testing Node itself. This diff would fix tests:
```diff
diff --git a/lib/ensure/__tests__/symlink.test.js b/lib/ensure/__tests__/symlink.test.js
index 22a0043..477b084 100644
--- a/lib/ensure/__tests__/symlink.test.js
+++ b/lib/ensure/__tests__/symlink.test.js
@@ -352,24 +352,6 @@ describe('fse-ensure-symlink', () => {
     })
   }
 
-  describe('fs.symlink()', () => {
-    const fn = fs.symlink
-    tests.forEach(test => {
-      const args = test[0].slice(0)
-      const nativeBehavior = test[1]
-      // const newBehavior = test[2]
-      if (nativeBehavior === 'file-success') fileSuccess(args, fn)
-      if (nativeBehavior === 'file-broken') fileBroken(args, fn)
-      if (nativeBehavior === 'file-error') fileError(args, fn)
-      if (nativeBehavior === 'file-dest-exists') fileDestExists(args, fn)
-      args.push('dir')
-      if (nativeBehavior === 'dir-success') dirSuccess(args, fn)
-      if (nativeBehavior === 'dir-broken') dirBroken(args, fn)
-      if (nativeBehavior === 'dir-error') dirError(args, fn)
-      if (nativeBehavior === 'dir-dest-exists') dirDestExists(args, fn)
-    })
-  })
-
   describe('ensureSymlink()', () => {
     const fn = ensureSymlink
     tests.forEach(test => {
@@ -410,24 +392,6 @@ describe('fse-ensure-symlink', () => {
     })
   })
 
-  describe('fs.symlinkSync()', () => {
-    const fn = fs.symlinkSync
-    tests.forEach(test => {
-      const args = test[0].slice(0)
-      const nativeBehavior = test[1]
-      // const newBehavior = test[2]
-      if (nativeBehavior === 'file-success') fileSuccessSync(args, fn)
-      if (nativeBehavior === 'file-broken') fileBrokenSync(args, fn)
-      if (nativeBehavior === 'file-error') fileErrorSync(args, fn)
-      if (nativeBehavior === 'file-dest-exists') fileDestExistsSync(args, fn)
-      args.push('dir')
-      if (nativeBehavior === 'dir-success') dirSuccessSync(args, fn)
-      if (nativeBehavior === 'dir-broken') dirBrokenSync(args, fn)
-      if (nativeBehavior === 'dir-error') dirErrorSync(args, fn)
-      if (nativeBehavior === 'dir-dest-exists') dirDestExistsSync(args, fn)
-    })
-  })
-
   describe('ensureSymlinkSync()', () => {
     const fn = ensureSymlinkSync
     tests.forEach(test => {
```

@manidlou @JPeer264 Thoughts here? Should we be testing Node's behavior here, or should we remove these tests? Should we get to the bottom of why it behaves differently here?

**Comment by JPeer264** [comment]
I am usually a very curious type of person and want to know why something is failing (or working :) ). But actually this is not the job of `fs-extra` to test against the node behavior, so for the PR itself I would just skip/remove these tests here. If there is time we could go deeper into this, but don't think it is necessary.

**Comment by RyanZim** [comment]
Removed the tests

**Review by manidlou — APPROVED** [review]
LGTM

**Pull request merged**
