### PR TITLE
BREAKING: fs.read() & fs.write() should return objects

### PR DESCRIPTION
**Pull request by RyanZim**
For forward-compat with `util.promisify()`

Resolves https://github.com/jprichardson/node-fs-extra/issues/436

Needs docs yet

### CODE REVIEW

**Comment by RyanZim** [comment]
Windows CI fails due to funky windows timestamps; unrelated to this change.

**Comment by yamboy1** [comment]
@RyanZim But why does the node.js v4 build pass and the v6 build fail?

**Comment by RyanZim** [comment]
@yamboy1 It's a 32-bit windows issue; nothing critical.

**Comment by yamboy1** [comment]
@RyanZim It's reasons like this why I prefer to use Linux

**Comment by yamboy1** [comment]
Windows just has too many bugs

**Pull request merged**
