### PR TITLE
createOutputStream

### PR DESCRIPTION
**Pull request by charlierudolph**
`fs.createWriteStream` but makes the parent directories if needed.

Happy to change the name if anyone has a better idea.

### CODE REVIEW

**Comment by jprichardson** [comment]
Awesome. To follow existing conventions of `outputJson` and `outputFile`, I think it'd be best to name it `outputWriteStream`.

**Comment by jprichardson** [comment]
Note, I'm willing to rename the entire prefix `output` of the three methods to something else if someone can think of something better.

**Comment by charlierudolph** [comment]
@jprichardson updated

Since "output" is replacing "write" in those names I went ahead and renamed this to `createOutputStream`.

**Comment by charlierudolph** [comment]
@jprichardson bump

**Comment by jprichardson** [comment]
Thanks for your patience on this. I'm not keen on the `output` substitution that I chose... I just haven't been able to think of anything better. But if you come up with something better, please let me know! I should be able to publish this within the next day or so. Feel free to ping me if that doesn't happen :)

**Comment by jprichardson** [comment]
Published: https://github.com/jprichardson/node-fs-extra/releases/tag/0.17.0 I changed it though. I think you'll like the new change, take a look and let me know.

**Comment by jprichardson** [comment]
Thanks for your contribution and help!

**Comment by charlierudolph** [comment]
Awesome. Thanks

**Pull request merged**
