### PR TITLE
Rewrite copySync

### LINKED ISSUE #83: Prevent copying a directory into itself
`fse.copy('src','src/dest')`  will create the dest  continues to recurse, and finally it throws an error `ENAMETOOLONG`

It links to AvianFlu/ncp#4

### PR DESCRIPTION
**Pull request by manidlou**
This is the rewrite of `copySync` to match `copy`. It should resolve #83, #198, and #464. Added corresponding tests for those issues. Also, removed the `fixtures` folder that was used by the `copy-sync-preserve-time.test.js`, instead the fixtures directory is created in the code.

Please let me know if anything doesn't look alright!

### CODE REVIEW

**Comment by manidlou** [comment]
IDK! it is so strange! the unit test for the case when `preserveTimestamp is true`, sometimes pass and sometimes doesn't! particularly on older node versions! :confused:

**Comment by manidlou** [comment]
Any ideas?

**Comment by RyanZim** [comment]
Will look at timestamps later.

**Comment by RyanZim** [comment]
@manidlou Spent a bunch of time messing with this, can't figure it out. I'm gonna say just put a conditional in place that that flaky test gets skipped on older node versions. @jprichardson Let me know if you disagree here.

**Comment by manidlou** [comment]
> @manidlou Spent a bunch of time messing with this, can't figure it out. I'm gonna say just put a conditional in place that that flaky test gets skipped on older node versions.

I agree. I played with it too, but no success! I am not sure but it seems like it is somehow related to node internals.

**Comment by manidlou** [comment]
If looks good, I will squash this.

**Comment by manidlou** [comment]
@jprichardson do you have any concerns regarding this?

**Comment by jprichardson** [comment]
Nice work @manidlou!

**Pull request merged**
