### PR TITLE
Provide 'EEXIST' code for "already exists" errors

### PR DESCRIPTION
**Pull request by urugator**
So we don't have to match against the error message.

Related: https://github.com/jprichardson/node-fs-extra/issues/461

### CODE REVIEW

**Comment by RyanZim** [comment]
Closing for the same reasons as https://github.com/jprichardson/node-fs-extra/pull/592.

**Comment by urugator** [comment]
Can't we pass `fs.constants.COPYFILE_EXCL` flag to `fs.copyFile` when `overwrite === true` and catch/rethrow the native error based on `errorOnExist`?
It would: 
- make the existence check atomic (current check isn't safe in concurrent env) 
- provide a way to handle the error meaningfully

**Comment by RyanZim** [comment]
The problem with that is that we still need to support environments that don't support `fs.copyFile`.

**Comment by urugator** [comment]
The fallback uses `createWriteStream`:

> The exclusive flag 'x' (O_EXCL flag in open(2)) ensures that path is newly created. On POSIX systems, path is considered to exist even if it is a symlink to a non-existent file. The exclusive flag may or may not work with network file systems.

Is that viable?

What is the suggested way to handle `errorOnExist` error?
I mean, the existence check isn't reliable enough as a guarantee for data loss prevention.
But it's also hard to use as a naive "let the user know" check, because the error is "indistinguishable" from others.    
So what's the use case? Should the `overwrite` and `errorOnExists` option even exist?

**Pull request closed without merging**
