### PR TITLE
Use Buffer.allocUnsafe() in enviroments that support it

### PR DESCRIPTION
**Pull request by RyanZim**
Resolves https://github.com/jprichardson/node-fs-extra/issues/391

### CODE REVIEW

**Comment by RyanZim** [comment]
Should I add a small `instanceof` test case for the buffer util?

**Comment by jprichardson** [comment]
> Should I add a small instanceof test case for the buffer util?

What do you mean?

**Comment by jprichardson** [comment]
Oh like `instanceof Buffer` inside of the Buffer util function? Use `Buffer.isBuffer()`

**Comment by manidlou** [comment]
> Should I add a small instanceof test case for the buffer util?

I am still not sure what you mean. You mean test if the returning result of the buffer util is an `instanceof Buffer`?

**Comment by RyanZim** [comment]
I was wondering if I should add a testcase to `lib/util/__test__` that tests the buffer util and ensures that it returns a buffer.

**Comment by manidlou** [comment]
> I was wondering if I should add a testcase to lib/util/__test__ that tests the buffer util and ensures that it returns a buffer.

Oh alright. Basically it is a good idea to have test for each feature that we add or change. However, I am not sure if this one is necessary.

**Pull request merged**
