### PR TITLE
util/stat: fix max call stack size exceeded

### LINKED ISSUE #678: [8.0.0] RangeError: Maximum call stack size exceeded at moveSync
- **Operating System:**
Windows [Version 10.0.17763.475]
- **Node.js version:**
v11.14.0
- **`fs-extra` version:**
v8.0.0

In the v7.0.1 is working fine!

```js
// Move
paths.forEach(path => (
  fs.moveSync(`${src}/${path}`, `${dest}${applyConfig(path, config)}`, { overwrite: true })
));
```

`(node:5924) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at isPathSeparator (path.js:38:25)
    at Object.resolve (path.js:169:13)
    at Object.toNamespacedPath (path.js:555:32)
    at Object.statSync (fs.js:869:41)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:143:21)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)`

### PR DESCRIPTION
**Pull request by manidlou**
fixes #678.

- resolve paths before parsing in `util/stat.js`
- add `util/stat` tests

### CODE REVIEW

**Comment by manidlou** [comment]
@jprichardson @RyanZim @JPeer264 please let me know if you have any concerns regarding this!

**Comment by manidlou** [comment]
rebased it. It should be ready now!

**Comment by manidlou** [comment]
@RyanZim the soonest that I can publish a patch is tonight, but if you can do it sooner, that'd be great if you handle that. Thank you!

**Comment by manidlou** [comment]
@RyanZim I went ahead and published a patch `v8.0.1`.

**Comment by RyanZim** [comment]
@manidlou Thanks, perfect!

**Pull request merged**
