### PR TITLE
allow preserveTimestamps when use move

### PR DESCRIPTION
**Pull request by bluelovers**
allow preserveTimestamps when use move
default: true

### CODE REVIEW

**Comment by jdalton** [comment]
@bluelovers Could you rebase this PR please.

**Comment by bluelovers** [comment]
updated merge

**Comment by jdalton** [comment]
@bluelovers If you make me a collaborator on your fork I can help clean up this PR.

**Comment by bluelovers** [comment]
@jdalton thx

**Comment by RyanZim** [comment]
@jprichardson Is this something you'd be interested in adding?

---

@bluelovers If we add this, this will need tests. Also, if https://github.com/jprichardson/node-fs-extra/pull/381 is merged ahead of this, equivalent functionality will need to be added to `moveSync`.

**Comment by bluelovers** [comment]
i have noidea how to make a good test lol

**Comment by jprichardson** [comment]
> @jprichardson Is this something you'd be interested in adding?

Yeah, I think it's worth it.

**Comment by RyanZim** [comment]
OK, if the code looks good to you, I'll squash-merge this.

**Comment by jprichardson** [comment]
> OK, if the code looks good to you, I'll squash-merge this.

SGTM

**Comment by RyanZim** [comment]
This looks like it might be conflicted beyond repair, any opposed to closing?

**Pull request closed without merging**
