### PR TITLE
Move docs to seperate docs folder

### LINKED ISSUE #298: API Docs
@jprichardson Thinking about the documentation: `fs-extra`'s docs are rather large. Perhaps we are approaching the size to consider using documentation.js or similar. For smaller libs, I consider this more trouble than it's worth, but I think I see some benefits here. Thoughts?

Of course, I doubt we can get this done in time for v1.0.0, but looking into the future, this might be the route to pursue.

Refs: https://github.com/jprichardson/node-fs-extra/issues/148.

### PR DESCRIPTION
**Pull request by RyanZim**
Resolves #298 

Also removed v0.12 support message from the README

### CODE REVIEW

**Comment by RyanZim** [comment]
Sure thing.

**Comment by RyanZim** [comment]
@jprichardson Done. Sorry so long in getting to this.

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
Thanks!

**Comment by RyanZim** [comment]
@jprichardson Anything else for v2?

**Comment by jprichardson** [comment]
> @jprichardson Anything else for v2?

I don't think so. Let's let things settle and we can plan on shipping v2 on Monday - that sound alright?

**Comment by RyanZim** [comment]
:+1: 

@mawni Can you get that PR for klaw-sync in the README ready before Monday, or shall I do it?

**Pull request merged**
