### PR TITLE
copy: support mode for copyFile

### PR DESCRIPTION
**Pull request by rickycao-qy**
This PR is to support reflink when copying files.

### CODE REVIEW

**Comment by RyanZim** [comment]
`mode` is only supported by Node 14+; and some of the options here overlap with some of our existing options. Long-term, I think moving to an API closer to `copyFile` makes sense, but I'm not sure if now is the right time. @manidlou thoughts?

**Comment by rickycao-qy** [comment]
> `mode` is only supported by Node 14+; and some of the options here overlap with some of our existing options. Long-term, I think moving to an API closer to `copyFile` makes sense, but I'm not sure if now is the right time. @manidlou thoughts?

Node.js with older version has the [optional parameter flag](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_copyfile_src_dest_flags_callback) which specifies modifiers for the copy operation. Can we just make this uniform in copy API

**Comment by rickycao-qy** [comment]
@manidlou @RyanZim Could you have a look, please

**Review by manidlou — COMMENTED** [review]
Sorry for late reply! I also agree that it is generally a good idea to be as compatible as possible with node core!

So, this option only applies to copying files, however `fs-extra` tries to abstract away the difficulties of differences between files and dirs for the end user.

IMHO, @rickycao-qy  we need to come up with a better name than `mode` for this option since it is not descriptive enough to let our users know this option is only used for copying files.

**Comment by rickycao-qy** [comment]
> Sorry for late reply! I also agree that it is generally a good idea to be as compatible as possible with node core!
> 
> So, this option only applies to copying files, however `fs-extra` tries to abstract away the difficulties of differences between files and dirs for the end user.
> 
> IMHO, @rickycao-qy we need to come up with a better name than `mode` for this option since it is not descriptive enough to let our users know this option is only used for copying files.

Hey, thanks for the reply. Personally I think this option is useful to copy dirs as we just apply this option to recursively copy files in dirs when applying to dirs. Or we can use a mofe descriptive option such as `copyFileMode`?

**Comment by manidlou** [comment]
I am ok with `copyFileMode`.

**Comment by RyanZim** [comment]
Closing as this is stale.

**Pull request closed without merging**
