### PR TITLE
missing EEXIST err.code

### PR DESCRIPTION
**Pull request by magicode**

### CODE REVIEW

**Comment by magicode** [comment]
Of course, All checks have failed
If you're interested. I'll fix it. like this
https://github.com/jprichardson/node-fs-extra/pull/296

**Comment by RyanZim** [comment]
I was never a huge fan of faking native errors; @manidlou what do you think of this?

**Comment by manidlou** [comment]
> I was never a huge fan of faking native errors

yeah me neither! @magicode will you please tell us why we are doing this? How is it necessary?

**Comment by magicode** [comment]
@manidlou 
To accurately distinguish between types of errors

**Comment by manidlou** [comment]
Then we have to handle all types of errors, `EEXIST` is just one of them. We also have to handle OS inconsistencies in error codes. IDK! I am not sure if I am convinced!

@jprichardson what do you think?

**Comment by jprichardson** [comment]
I have no strong feelings here. I defer to you @RyanZim or @manidlou. I will say that if we need to complicate the code, it better be for a really good reason.

**Comment by RyanZim** [comment]
Closing; faking error codes is a mess, not going there.

**Comment by magicode** [comment]
@RyanZim  OK. revert this https://github.com/jprichardson/node-fs-extra/pull/296/files

**Comment by RyanZim** [comment]
That'd be semver-major, but I'm open to it. @magicode care to make the PR?

**Comment by magicode** [comment]
@RyanZim  Sorry. I thought it was the current code.

**Pull request closed without merging**
