### PR TITLE
Modify to follow the rules of the new 'standard' and 'standard-markdown'

### PR DESCRIPTION
**Pull request by abetomo**
Upgrade standard.
Fix the error code.

### CODE REVIEW

**Comment by JPeer264** [comment]
@abetomo thanks for your PR, seems like some checks failed on Travis. Can you please resolve them?

**Comment by abetomo** [comment]
Thanks for the review.
Standard-markdown seems to be bad. I will check the details.

**Comment by abetomo** [comment]
Since it was a `standard-markdown` bug, I opened PR in that project.
https://github.com/zeke/standard-markdown/pull/25

**Comment by abetomo** [comment]
I added an argument as an interim fix until the https://github.com/zeke/standard-markdown/pull/25 is merged.

**Comment by manidlou** [comment]
I would say rebase this and merge it to `v8-dev`. We'll figure it out there!

**Comment by JPeer264** [comment]
Still needs a rebase though.

**Comment by RyanZim** [comment]
Closing in favor of https://github.com/jprichardson/node-fs-extra/pull/636.

**Pull request closed without merging**
