### PR TITLE
Remove copy test fixtures directory, create with code

### LINKED ISSUE #150: Remove test file fixtures, create with code.

### PR DESCRIPTION
**Pull request by manidlou**
Refactored `copy` and `copySync` preserve timestamp test. Should resolve #150. We don't have any fixtures directory in our codebase anymore (at least I couldn't find any!) :smile:

### CODE REVIEW

**Comment by manidlou** [comment]
Ah! I forgot to skip that test for old node versions!

**Comment by manidlou** [comment]
I squash this.

**Comment by manidlou** [comment]
@jprichardson ping?!

**Comment by RyanZim** [comment]
Re-reviewed and merged myself since it's just tests.

**Pull request merged**
