### PR TITLE
Fixed issue with slash separated paths on windows

### PR DESCRIPTION
**Pull request by felicienfrancois**

### CODE REVIEW

**Comment by felicienfrancois** [comment]
Tested with the following paths:
```
path\to\some\dir=> path\to\some
path\to\some\dir\ => path\to\some\dir
path/to/some/dir=> path\to\some
path/to/some/dir/ => path\to\some\dir
dir => .
dir\ => dir
dir/ => dir
```

**Comment by jprichardson** [comment]
I'd like to accept this, but I can't until I get all of the other Windows issues currently fixed as report by Appveyor.

**Comment by jprichardson** [comment]
OK, all Appveyor Windows tests are passing now. It's not quite clear to me what problem this is solving?

**Comment by felicienfrancois** [comment]
Before the fix, the copy method were not working correctly when the dest path was slash separated instead of anti-slash separated.
Additionally, using the copy method with a relative dir without any separator were not working

Before the processing of dest dir was:
`"path\to\some\dir"` => `"path\to\some"`        OK
`"path\to\some\dir\"` => `"path\to\some\dir"`  OK
`"path/to/some/dir"` => `""` FAIL
`"path/to/some/dir/"` => `""` FAIL
`"dir"` => `""` FAIL
`"dir\"` => `"dir"`  OK
`"dir/"` => "" FAIL
```

Now it is:
`"path\to\some\dir"` => `"path\to\some"`        OK
`"path\to\some\dir\"` => `"path\to\some\dir"`  OK
`"path/to/some/dir"` => `"path\to\some"`        OK
`"path/to/some/dir/"` => "path\to\some\dir"     OK
`"dir"` => "."     OK
`"dir\"` => "dir"     OK
`"dir/"` => "dir"     OK
```

This was due to the use of split(path.sep) (IE `\` on windows) on a possibly not normalized path.
The ` || "."` addition fix the bug for relative dir without separator

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
> @jprichardson ping?

I'm not sure here. Maybe we need to normalize the paths now? This issue is pretty old.

**Comment by RyanZim** [comment]
Closing this PR since resolving the merge conflicts would be more work than re-implementing. If anyone has a similar issue, please open an issue in the issue tracker with a reduced test case; we can go from there.

**Pull request closed without merging**
