### PR TITLE
Rewrite copy

### LINKED ISSUE #83: Prevent copying a directory into itself
`fse.copy('src','src/dest')`  will create the dest  continues to recurse, and finally it throws an error `ENAMETOOLONG`

It links to AvianFlu/ncp#4

### PR DESCRIPTION
**Pull request by manidlou**
Started #374.

Fixes #83 and #198.

This implementation uses `recursive` pattern for copying directories. `recursive` pattern has shown better performance than `Promise` ([copy-benchmark](https://github.com/manidlou/benchmark-fs-extra-copy)). If this looks good, then we will apply `fs.copyFile()` to it.

Any feedback appreciated! :smile:

### CODE REVIEW

**Comment by manidlou** [comment]
Aah! I forgot node 4 cannot read new es `{}` module loading syntax!

**Comment by RyanZim** [comment]
@manidlou Not sure why this is WIP? We should probably merge this into a `develop` branch and have a separate PR for `fs.copyFile` changes.

**Comment by manidlou** [comment]
> @manidlou Not sure why this is WIP?

Yeah, primarily because of `fs.copyFile`.

> We should probably merge this into a develop branch and have a separate PR for fs.copyFile changes.

Good idea! :+1:

**Comment by jprichardson** [comment]
Stellar work @manidlou! Please squash the changes to account for the destructuring fix, and then it LGTM.

**Comment by manidlou** [comment]
> Please squash the changes to account for the destructuring fix, and then it LGTM.

Sure thing.

**Comment by manidlou** [comment]
Squash done! :smiley:

**Comment by RyanZim** [comment]
Will merge when I’m on desktop.

**Comment by manidlou** [comment]
@RyanZim ping?!

**Comment by RyanZim** [comment]
Thanks for the ping @manidlou, I totally forgot this. Merged to new `develop` branch.

**Pull request merged**
